<?php

namespace App\Services\RAG;

use App\Models\Book;
use App\Services\AI\Contracts\EmbeddingProviderInterface;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Retrieves the most relevant content chunks for a query using
 * pgvector cosine distance (<=> operator).
 */
class RetrievalService
{
    public function __construct(
        private readonly EmbeddingProviderInterface $embedder,
    ) {
    }

    public function search(
        string $originalQuery,
        string $normalizedQuery,
        int $limit = 10,
        ?string $chapterId = null,
        ?string $excerptText = null
    ): \Illuminate\Support\Collection {
        // 1. If an exact excerpt is requested, search direct excerpt matches first
        if (!empty($excerptText)) {
            $excerptMatches = $this->searchByExcerpt($excerptText, $chapterId, $limit);
            if ($excerptMatches->isNotEmpty()) {
                Log::info('RetrievalService: found direct excerpt matches', [
                    'excerpt' => substr($excerptText, 0, 50),
                    'count'   => $excerptMatches->count(),
                ]);
                return $excerptMatches;
            }
        }

        $k_rrf = 60; // Standard RRF tuning constant

        // Ensure we only query vectors generated by the active embedding provider (Req 9.1)
        try {
            $activeProvider = \App\Models\AdminSetting::where('key', 'ai_embedding_provider')->first()?->value
                ?: config('ai.embedding_provider', 'voyage');
        } catch (\Throwable) {
            $activeProvider = config('ai.embedding_provider', 'voyage');
        }

        // Pass 'query' input_type for models that support it
        $queryVector = $this->embedder->embed($normalizedQuery, 'query');
        $vectorStr   = '[' . implode(',', $queryVector) . ']';

        $isVoyage = $activeProvider === 'voyage';
        $activeModel = config("ai.{$activeProvider}.embedding_model", $isVoyage ? 'voyage-4' : 'qwen3-embedding:0.6b');
        $activeDimension = (int) config("ai.{$activeProvider}.embedding_dimension", 1024);

        if ($isVoyage) {
            $semanticFrom = "FROM content_chunks c JOIN content_chunk_embeddings ce ON ce.chunk_id = c.id";
            $semanticEmbedding = "ce.embedding";
            $semanticProviderCheck = "ce.provider = ? AND ce.model = ? AND ce.dimension = ?";
        } else {
            $semanticFrom = "FROM content_chunks c";
            $semanticEmbedding = "c.embedding";
            $semanticProviderCheck = "c.embedding_provider = ? AND c.embedding_model = ? AND vector_dims(c.embedding) = ?";
        }

        $cleanLexical = preg_replace('/^(?:please\s+)?(?:can you\s+)?(?:give me\s+(?:a\s+)?quiz\s+(?:on|about|from)?|quiz me\s+(?:on|about|from)?|test me\s+(?:on|about|from)?|create a quiz\s+(?:on|about|from)?|explain|tell me (?:about|more about)|describe|detail|discuss|elaborate on|what is|what are|how does|how do)\s+/i', '', $normalizedQuery);
        $cleanLexical = preg_replace('/\b(?:specifically|in detail|thoroughly|deeply|briefly)\b/i', '', $cleanLexical);
        // Strip parenthetical chapter indicators like (Boqonnaa 7) or (Chapter 7)
        $cleanLexical = preg_replace('/\((?:boqonnaa|boqonna|chapter|ch|kutaa|ምዕራፍ)\s*\d+\)/iu', '', $cleanLexical);
        // Strip Afaan Oromoo question/framing words
        $cleanLexical = preg_replace('/\b(?:wa\'ee|waaye|waan|nati\s+himi|naaf\s+himi|naaf\s+ibsi|maalidha|maali|akkamitti|akkam|boqonnaa|boqonna|kutaa|mee|deebisi)\b/iu', ' ', $cleanLexical);
        // If query contains Amharic script alongside latin terms, strip Amharic framing to keep English search terms clean
        if (preg_match('/[a-zA-Z]{3,}/', $cleanLexical)) {
            $cleanLexical = preg_replace('/[\x{1200}-\x{137F}]+/u', ' ', $cleanLexical);
        }
        $cleanLexical = trim(preg_replace('/[^\p{L}\p{N}\s\-]/u', ' ', $cleanLexical));
        $cleanLexical = trim(preg_replace('/\s+/', ' ', $cleanLexical));
        if (empty($cleanLexical)) {
            $cleanLexical = $normalizedQuery;
        }

        try {
            $rows = DB::select(
                <<<SQL
                WITH semantic_search AS (
                    SELECT c.id, (1 - ({$semanticEmbedding} <=> ?::vector)) AS score,
                           ROW_NUMBER() OVER (ORDER BY {$semanticEmbedding} <=> ?::vector) as rank
                    {$semanticFrom}
                    WHERE c.embedding_status = 'ready'
                      AND {$semanticEmbedding} IS NOT NULL
                      AND {$semanticProviderCheck}
                      AND c.book_id IN (SELECT id FROM books WHERE status = 'published')
                      AND c.chunk_text NOT ILIKE '%table of contents%'
                      AND c.chunk_text NOT ILIKE '%list of figures%'
                      AND c.chunk_text NOT ILIKE '%list of tables%'
                      AND LENGTH(TRIM(REGEXP_REPLACE(c.chunk_text, '<[^>]+>', '', 'g'))) >= 80
                    ORDER BY rank
                    LIMIT 60
                ),
                lexical_search AS (
                    SELECT id, score, ROW_NUMBER() OVER (ORDER BY score DESC) as rank
                    FROM (
                        SELECT c.id,
                               GREATEST(
                                   ts_rank(c.search_vector, websearch_to_tsquery('english', ?)),
                                   ts_rank(c.search_vector, plainto_tsquery('english', ?)),
                                   ts_rank(c.search_vector, websearch_to_tsquery('english', ?)),
                                   ts_rank(c.search_vector, plainto_tsquery('english', ?))
                               ) AS score
                        FROM content_chunks c
                        WHERE c.embedding_status = 'ready'
                          AND c.book_id IN (SELECT id FROM books WHERE status = 'published')
                          AND (
                              c.search_vector @@ websearch_to_tsquery('english', ?)
                              OR c.search_vector @@ plainto_tsquery('english', ?)
                              OR c.search_vector @@ websearch_to_tsquery('english', ?)
                              OR c.search_vector @@ plainto_tsquery('english', ?)
                          )
                          AND c.chunk_text NOT ILIKE '%table of contents%'
                          AND c.chunk_text NOT ILIKE '%list of figures%'
                          AND c.chunk_text NOT ILIKE '%list of tables%'
                          AND LENGTH(TRIM(REGEXP_REPLACE(c.chunk_text, '<[^>]+>', '', 'g'))) >= 80
                    ) sub
                    WHERE score > 0
                    ORDER BY rank
                    LIMIT 60
                )
                SELECT
                    c.id, c.chunk_text, c.book_id, c.page_number, c.structural_context, c.section_id,
                    ch.id as chapter_id,
                    ch.title as chapter_title,
                    sec.title as section_title,
                    COALESCE(s.score, 0) as vector_score,
                    COALESCE(l.score, 0) as keyword_score,
                    COALESCE(s.rank, 1000) as vector_rank,
                    COALESCE(l.rank, 1000) as keyword_rank,
                    (
                        (CASE WHEN ?::uuid IS NOT NULL AND sec.chapter_id = ?::uuid THEN 0.35 ELSE 0.0 END) +
                        (CASE WHEN s.rank IS NOT NULL THEN 1.0 / (? + s.rank) ELSE 0 END) +
                        (CASE WHEN l.rank IS NOT NULL THEN 1.0 / (? + l.rank) ELSE 0 END)
                    ) as rrf_score
                FROM content_chunks c
                LEFT JOIN sections sec ON sec.id = c.section_id
                LEFT JOIN chapters ch ON ch.id = sec.chapter_id
                LEFT JOIN semantic_search s ON s.id = c.id
                LEFT JOIN lexical_search l ON l.id = c.id
                WHERE (s.id IS NOT NULL OR l.id IS NOT NULL)
                  AND LENGTH(TRIM(REGEXP_REPLACE(c.chunk_text, '<[^>]+>', '', 'g'))) >= 80
                ORDER BY rrf_score DESC
                LIMIT ?
                SQL,
                [
                    // semantic bindings (vector, vector, provider, model, dimension)
                    $vectorStr, $vectorStr, $activeProvider, $activeModel, $activeDimension,
                    // lexical score bindings (rank1, rank2, rank3, rank4)
                    $cleanLexical, $cleanLexical, $cleanLexical, $cleanLexical,
                    // lexical filter bindings (match1, match2, match3, match4)
                    $cleanLexical, $cleanLexical, $cleanLexical, $cleanLexical,
                    // chapter boost bindings (? is not null, sec.chapter_id = ?)
                    $chapterId, $chapterId,
                    // RRF bindings
                    $k_rrf, $k_rrf,
                    // limit
                    $limit
                ]
            );
        } catch (\Illuminate\Database\QueryException $e) {
            Log::error('RetrievalService: Database query failed', [
                'error' => $e->getMessage(),
                'query' => substr($originalQuery, 0, 80),
            ]);
            throw new \App\Exceptions\RAGRetrievalException('Database retrieval failed: ' . $e->getMessage(), 'database', $e);
        } catch (\Throwable $e) {
            Log::error('RetrievalService: Hybrid RRF query failed', [
                'error' => $e->getMessage(),
                'query' => substr($originalQuery, 0, 80),
            ]);
            throw new \App\Exceptions\RAGRetrievalException('Retrieval stage failed: ' . $e->getMessage(), 'retrieval', $e);
        }

        $chunks = array_map(function ($row) {
            $context = is_string($row->structural_context) ? json_decode($row->structural_context, true) : ($row->structural_context ?: []);
            if (!isset($context['heading'])) {
                $context['heading'] = $row->section_title ?: ($row->chapter_title ?: 'General Context');
            }
            return [
                'id'                 => $row->id,
                'chunk_text'         => $row->chunk_text,
                'rrf_score'          => round((float) $row->rrf_score, 4),
                'vector_score'       => round((float) $row->vector_score, 4),
                'keyword_score'      => round((float) $row->keyword_score, 4),
                'vector_rank'        => (int) $row->vector_rank,
                'keyword_rank'       => (int) $row->keyword_rank,
                'book_id'            => $row->book_id,
                'chapter_id'         => $row->chapter_id ?? null,
                'chapter_title'      => $row->chapter_title ?? null,
                'section_id'         => $row->section_id ?? null,
                'section_title'      => $row->section_title ?? null,
                'page_number'        => $row->page_number,
                'structural_context' => $context,
            ];
        }, $rows);

        // Filter out irrelevant chunks (e.g., out-of-domain conversational queries)
        $chunks = array_filter($chunks, function ($chunk) use ($activeProvider) {
            // Voyage embeddings have dot products typically < 0.10. Gemini is usually > 0.60.
            $semanticThreshold = $activeProvider === 'voyage' ? 0.02 : 0.35;
            $lexicalThreshold = 0.05; // Ignore extremely weak partial lexical matches
            return $chunk['vector_score'] >= $semanticThreshold || $chunk['keyword_score'] >= $lexicalThreshold;
        });

        Log::info('RetrievalService: retrieved chunks via Hybrid Search', [
            'query'     => substr($originalQuery, 0, 80),
            'count'     => count($chunks),
            'top_score' => $chunks[0]['rrf_score'] ?? null,
        ]);

        return collect($chunks)->values();
    }

    public function searchByExcerpt(string $excerptText, ?string $chapterId = null, int $limit = 5): \Illuminate\Support\Collection
    {
        $query = DB::table('content_chunks as c')
            ->join('sections as sec', 'sec.id', 'c.section_id')
            ->join('chapters as ch', 'ch.id', 'sec.chapter_id')
            ->where('c.embedding_status', 'ready')
            ->where('c.book_id', function ($sub) {
                $sub->select('id')->from('books')->where('status', 'published')->limit(1);
            });

        if (!empty($chapterId)) {
            $query->where('sec.chapter_id', $chapterId);
        }

        $query->whereRaw("LENGTH(TRIM(REGEXP_REPLACE(c.chunk_text, '<[^>]+>', '', 'g'))) >= 80");

        $query->where(function ($q) use ($excerptText) {
            $q->whereRaw("c.search_vector @@ plainto_tsquery('english', ?)", [$excerptText])
              ->orWhere('sec.title', 'ILIKE', '%' . $excerptText . '%')
              ->orWhere('c.chunk_text', 'ILIKE', '%' . $excerptText . '%');
        });

        $escaped = DB::getPdo()->quote($excerptText);
        $rows = $query->select([
            'c.id',
            'c.chunk_text',
            'c.book_id',
            'c.page_number',
            'c.structural_context',
            'c.section_id',
            'ch.id as chapter_id',
            'ch.title as chapter_title',
            'sec.title as section_title',
            DB::raw("ts_rank(c.search_vector, plainto_tsquery('english', {$escaped})) as keyword_score"),
        ])
        ->orderByDesc('keyword_score')
        ->limit($limit)
        ->get();

        return collect($rows)->map(function ($row) {
            $context = is_string($row->structural_context) ? json_decode($row->structural_context, true) : ($row->structural_context ?: []);
            if (!isset($context['heading'])) {
                $context['heading'] = $row->section_title ?: ($row->chapter_title ?: 'General Context');
            }
            return [
                'id'                 => $row->id,
                'chunk_text'         => $row->chunk_text,
                'rrf_score'          => 1.0,
                'vector_score'       => 0.9,
                'keyword_score'      => round((float) ($row->keyword_score ?? 1.0), 4),
                'vector_rank'        => 1,
                'keyword_rank'       => 1,
                'book_id'            => $row->book_id,
                'chapter_id'         => $row->chapter_id,
                'chapter_title'      => $row->chapter_title,
                'section_id'         => $row->section_id,
                'section_title'      => $row->section_title,
                'page_number'        => $row->page_number,
                'structural_context' => $context,
            ];
        });
    }

    public function getChapterChunks(int $chapterNumber): \Illuminate\Support\Collection
    {
        $rows = DB::table('content_chunks')
            ->join('sections', 'content_chunks.section_id', '=', 'sections.id')
            ->join('chapters', 'sections.chapter_id', '=', 'chapters.id')
            ->join('books', 'content_chunks.book_id', '=', 'books.id')
            ->where('books.status', 'published')
            ->where(function($query) use ($chapterNumber) {
                $query->where('chapters.order', $chapterNumber)
                      ->orWhere('chapters.title', 'ILIKE', "Ch-{$chapterNumber}:%")
                      ->orWhere('chapters.title', 'ILIKE', "Chapter {$chapterNumber}:%")
                      ->orWhere('chapters.title', 'ILIKE', "Ch {$chapterNumber}:%")
                      ->orWhere('chapters.title', 'ILIKE', "Chapter-{$chapterNumber}:%")
                      ->orWhere('chapters.title', 'ILIKE', "{$chapterNumber}.%")
                      ->orWhereRaw("chapters.title ~* ('^' || ? || '\s+')", [$chapterNumber]);
            })
            ->where('content_chunks.embedding_status', 'ready')
            ->whereRaw("LENGTH(TRIM(REGEXP_REPLACE(content_chunks.chunk_text, '<[^>]+>', '', 'g'))) >= 80")
            ->orderBy('sections.order')
            ->orderBy('content_chunks.chunk_index')
            ->select('content_chunks.*', 'chapters.title as chapter_title', 'sections.title as section_title')
            ->get();

        return $rows->map(function ($row) {
            $context = is_string($row->structural_context) ? json_decode($row->structural_context, true) : [];
            if (!isset($context['heading'])) {
                $context['heading'] = $row->section_title ?: $row->chapter_title;
            }
            return [
                'id'                 => $row->id,
                'chunk_text'         => $row->chunk_text,
                'rrf_score'          => 1.0,
                'chapter_title'      => $row->chapter_title,
                'section_title'      => $row->section_title,
                'book_id'            => $row->book_id,
                'page_number'        => $row->page_number,
                'structural_context' => $context,
            ];
        });
    }

    public function getChunksByIds(array $ids): \Illuminate\Support\Collection
    {
        if (empty($ids)) {
            return collect();
        }

        $rows = DB::table('content_chunks')
            ->leftJoin('sections', 'sections.id', '=', 'content_chunks.section_id')
            ->leftJoin('chapters', 'chapters.id', '=', 'sections.chapter_id')
            ->select('content_chunks.*', 'chapters.title as chapter_title', 'sections.title as section_title')
            ->whereIn('content_chunks.id', $ids)
            ->get();

        return $rows->map(function ($row) {
            $context = is_string($row->structural_context) ? json_decode($row->structural_context, true) : ($row->structural_context ?: []);
            if (!isset($context['heading'])) {
                $context['heading'] = $row->section_title ?: ($row->chapter_title ?: 'General Context');
            }
            return [
                'id'                 => $row->id,
                'chunk_text'         => $row->chunk_text,
                'rrf_score'          => 0.0,
                'vector_score'       => 0.0,
                'keyword_score'      => 0.15, // Moderate continuity boost
                'book_id'            => $row->book_id,
                'page_number'        => $row->page_number,
                'structural_context' => $context,
            ];
        });
    }
}
